### ISSUE TITLE
Security warning

### ISSUE THREAD

**Issue by kieranpaul** [ccoenraets/OpenFB#21]
I can get this working in the browser but I keep getting a Security warning in my phonegap app?

I'm sure if I am setting my Facebook app up correctly.

Any help would be must appreciated :)

**Comment by Louis777** [comment]
I have tried all solutions on this thread and many others, none seem to help me. I am getting the Success Security Warning message on my android device. It works very well on my browser (I am using Visual Studio 2013 update 4).

I do have the following:

InAppBowerser version 1.0.0, installed as a plugin
On my FB Dev. Setting -> Basic I have: http://localhost:4437/
Om my FB Dev. Setting -> Advance I have: https://www.facebook.com/connect/login_success.html
Side Notes:

Initially I was getting "the redirect_uri is not supported", I fixed this by placing:

runningInCordova = true;
right after this

document.addEventListener("deviceready", function () {
        runningInCordova = true;
        alert("runningInCordova");
    }, false);

in the OpenFB.js file, since on my adroid device the above listener was not executing. This now gives me access to the FB login screen.

But after login in I get the Success Security Warning message. I have spent 3 days trying to resolved this issue. I have tried many, many things but nothing seems to works. I am sure there is a solution out there.

Is there a way to fix this?

Please help, Thank you in advance.

Louis

**Comment by eugenemaning** [comment]
I am willing to help since I have already faced this issue. Can you send a
snippet of your code?

**Comment by Louis777** [comment]
I would really appreciate your help:

Here is how I call it:
    openFB.init({ appId: '5555555555555', tokenStore: window.localStorage });
    openFB.api({
        path: '/me',
        success: function (data) {
            console.log(JSON.stringify(data));
            document.getElementById("userFBID").innerHTML = data.id;
            document.getElementById("userFullName").innerHTML = data.name;
            document.getElementById("userEmail1").innerHTML = data.email;
            SetDBConn();
        },
        error: errorHandler
    });

My openfb.js is the same the one you posted here:

https://github.com/eugenemaning/openfb.js/blob/master/openfb.js

with the exception that I had to add [ runningInCordova = true; ] after the addEventListener, since it doesn't seem to execute when running in my Android device, the code now looks like this:

    document.addEventListener("deviceready", function () {
        runningInCordova = true;
    }, false);
    runningInCordova = true;  //I added to make sure it know that we are running Cordova

If I don't add it, it says: [ the redirect_uri is not supported ]

Thanks in advance.

Louis

**Comment by Louis777** [comment]
I am sorry for being a pest, but I can't find any solution for my issue. It seems to be a very easy solution, but I can't find it. I've spend many days on this already.

Please help.

**Comment by ccoenraets** [comment]
If you add to manually add runningInCordova = true, it probably you didn't include cordova.js in index.html:

```
<script src="cordova.js"></script>
```
Note: cordova.js doesn't have to be available (and shouldn't be) in your www folder. It is automatically injected by the Cordova build process.

Also make sure you have the inappbrowser plugin installed:

```
cordova plugins add org.apache.cordova.inappbrowser
```

**Comment by superandrew** [comment]
I am having this problem, too. I am literally cursing myself for using this library. I am using inappbrowser, I was forced to set runningInCordova = true because in android it didn't get recognized (I am building with pg:build)
