### ISSUE TITLE
Phonegap Build Android net::ERR_CONNECTION_REFUSED(http://localhost:8100

### ISSUE THREAD

**Issue by jsrosas** [ccoenraets/OpenFB#59]
Hey All. thanks in advance for any help you can give me.  I got OpenFB login working on my locahost and on my my device using ionic run android.  It logs in with our error.  But I get this error when I use PhoneGap Build to get an apk file.  I download it to my device, I run it and get the error: net::ERR_CONNECTION_REFUSED(http://localhost:8100

Any Idea why?

**Comment by Ankur-Jat** [comment]
May be because of "local server" issue in android os. I mean your app is not allowed to fetch data from local server from android os.

**Comment by jsrosas** [comment]
The weird thing is that the app works from android os when i do ionic run android.  How do I resolve this issue?

**Comment by jsrosas** [comment]
So i have tried setting my oath link to https://www.facebook.com/connect/login_success.html but the setting on the Facebook App will not allow me to set this url as the site URL.  Any solutions?

**Comment by ccoenraets** [comment]
The OAuth redirect URL can be hosted on any domain your device has access to. So URLs like http://localhost/oauthcallback.html will not work because the localhost you are referring to is your computer that your device has no way to reach in that way. So either host the redirect URL on a server your device has access to, or, for testing, make sure your device and computer are on the same subnet and replace localhost with the local ip of your computer... something like 192.168.1.3
